# ===============================================================
#                       Global Settings
# ===============================================================
settings:
  # Language Selection
  # Supported: en (English), vi (Vietnamese)
  language: en

  # Debug Mode (for printing debug messages to console)
  debug: false

  # Data Persistence Interval
  # 20 ticks = 1 second, default: 5 minutes
  save-interval: 6000

# ===============================================================
#                      Spawner Core Mechanics
# ===============================================================
spawner:
  # Spawner Configuration
  default-entity: PIG
  min-mobs: 1                 # Minimum mob spawn count
  max-mobs: 4                 # Maximum mob spawn count
  range: 16                   # Player proximity for activation (blocks)
  delay: 600                  # Base spawn delay (ticks) - 30 seconds

  # Resource Management
  max-storage-pages: 1        # Storage page(s) per spawner (1 page = 45 slots)
  max-stored-exp: 1000        # Maximum storable experience points
  max-stack-size: 1000        # Maximum spawner stack size

  # Advanced Features
  allow-exp-mending: true     # Repair items using stored experience
  allow-toggle-equipment-drops: true
  allow-grief: false          # Prevent explosions destroying spawners
  activate-on-place: true     # Immediate spawner activation

# ===============================================================
#                   Spawner Breaking Mechanics
# ===============================================================
spawner-break:
  enabled: true

  # Permitted Breaking Tools
  required-tools:
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE

  # Breaking Penalties
  durability-loss-per-spawner: 1

  # Silk Touch Requirements
  silk-touch:
    required: true
    level: 1

  # Dropping Configurations
  drop-stack:
    amount: 64  # Maximum dropped items per break

# ===============================================================
#                     Economic Integration
# ===============================================================

# Available options: disabled, EconomyShopGUI, EconomyShopGUI-Premium, ShopGUIPlus
shop-integration: EconomyShopGUI

# Formating price with currency symbol: K, M, B, T by default in the message file
formated-price: true

tax:
  enabled: false
  rate: 10.0  # % tax on sales

# ===============================================================
#                  Hopper Mechanics (Experimental)
# ===============================================================
# Not recommended for large servers
hopper:
  enabled: false
  items-per-transfer: 1
  check-interval: 20

# ===============================================================
#                     Plugin Update Checker
# ===============================================================
update-checker:
  enabled: true
  check-interval: 24          # Hours between update checks
  notify-ops: true            # Alert server operators
  notify-on-join: true        # Notify on server entry (for players have update permission)