# ===============================================================
#                       Global Settings
# ===============================================================
settings:
  # Language Selection
  # Supported: en_US (English), vi_VN (Vietnamese), zh_CN (Simplified Chinese)
  # You can also use custom language files by placing them in the messages folder and setting the language to the file name
  language: en_US

  # Debug Mode (for printing debug messages to console)
  debug: false

  # Data Persistence Interval
  # 20 ticks = 1 second, default: 5 minutes
  save-interval: 6000

# ===============================================================
#                      Spawner Core Mechanics
# ===============================================================
spawner:
  # Spawner Configuration
  default-entity: PIG
  min-mobs: 1                 # Minimum mob spawn count
  max-mobs: 4                 # Maximum mob spawn count
  range: 16                   # Player proximity for activation (blocks)
  delay: 600                  # Base spawn delay (ticks) - 30 seconds

  # Resource Management
  max-storage-pages: 1        # Storage page(s) per spawner (1 page = 45 slots)
  max-stored-exp: 1000        # Maximum storable experience points
  max-stack-size: 1000        # Maximum spawner stack size

  # Advanced Features
  allow-exp-mending: true     # Repair items using stored experience
  allow-toggle-equipment-drops: true
  allow-grief: false          # Prevent explosions destroying spawners
  activate-on-place: true     # Immediate spawner activation

# ===============================================================
#                   Spawner Breaking Mechanics
# ===============================================================
spawner-break:
  enabled: true

  # Permitted Breaking Tools
  required-tools:
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE

  # Breaking Penalties
  durability-loss-per-spawner: 1

  # Silk Touch Requirements
  silk-touch:
    required: true
    level: 1

  # Dropping Configurations
  drop-stack:
    amount: 64  # Maximum dropped items per break

# ===============================================================
#                     Aesthetic Features
# ===============================================================
# Aesthetic features may impact server performance, turn off if you want maximum performance

# Hologram Configuration
hologram:
  enabled: false
  see-through: false      # Whether hologram should be visible through blocks
  shadowed-text: true     # Whether hologram text is shadowed
  height: 1.6             # Height of the hologram above the spawner
  offset:                 # Offset of the hologram from the spawner
    x: 0.5
    z: 0.5

# Particle Configuration
particles:
  loot-spawn: true        # Particle effect when spawner loot is spawned
  spawner-stack: true     # Particle effect when spawners are stacked
  spawner-activate: true  # Particle effect when spawner is activated

# ===============================================================
#                     Economic Integration
# ===============================================================
# Available Options:
# - auto: Automatically detect supported shop plugins
# - EconomyShopGUI
# - EconomyShopGUI-Premium
# - ShopGUIPlus
# - zShop (with Vault only)
# - disabled: No shop integration
shop-integration: auto

# Formating price with currency symbol: K, M, B, T by default in the message file
formated-price: true

tax:
  enabled: false
  rate: 10.0  # % tax on sales

# Logging sales transactions to file
logging:
  enabled: true
  file-path: "shop-logs/sales.log"

# ===============================================================
#                  Hopper Mechanics (Experimental)
# ===============================================================
# Not recommended for large servers
hopper:
  enabled: false
  items-per-transfer: 1
  check-interval: 20

# ===============================================================
#                     Plugin Update Checker
# ===============================================================
update-checker:
  enabled: true
  check-interval: 24          # Hours between update checks
  notify-ops: true            # Alert server operators
  notify-on-join: true        # Notify on server entry (for players have update permission)